name: Security Scan

on: [push, pull_request]

jobs:
  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run security scan
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, python, java

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
